### ISSUE TITLE
tiny gcode visualizer lib for tiny webserver

### ISSUE THREAD

**Issue by mkeyno** [Ultimaker/GCodeGenJS#1]
sorry to open ticket for my question but actually I'm looking for light gcode visualizer or probably cad2gcode convertor in my webpage , but this webpage hosted on tiny ESP826612F module which is connected to Arduino GRBL gcode interpreter by serial line, so I should have great care about its weight , My plan is just connect to wifi module and open the browser and do designated CAM job.,As I'm not pro in client side script like JavaScript I was hopping could have good advise here, do you suggest to make some plugin from such library so I shouldn't have to download or call all library ?
thanks

**Comment by BagelOrb** [comment]
This repo is about generating gcode from scratch without any 3d model.

There is no such thing as a lightweight cad2gcode converter.

I don't know about any JavaScript gcode visualize, but there are enough online gcode visualizers. It's probably better if you check if any of those is open source. I know tiny-G is a nice online viewer.
